# Generated by Django 4.2.10 on 2024-02-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_offer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image_url",
            field=models.CharField(max_length=99999),
        ),
    ]
